# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Run the tests for our iOS project"
  lane :run_tests do
    scan(
      scheme: "ECommerce", # Replace with your app's scheme
      device: "iPhone SE (3rd generation)",     # Replace with the simulator/device you want
      clean: true
    )
  end
end
